name: omniwave
description: Omniwave Music Player
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'
  flutter: '>=3.7.0'

dependencies:
  authentication_repository:
    path: packages/authentication_repository
  bloc: ^8.1.0
  bloc_concurrency: ^0.2.1
  envied: ^0.3.0
  equatable: ^2.0.5
  firebase_core: ^2.9.0
  flex_color_scheme: ^7.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_localizations:
    sdk: flutter
  intl: any
  just_audio: ^0.9.31
  just_audio_mpv: ^0.1.6
  multi_split_view: ^2.2.0
  music_repository:
    path: packages/music_repository
  rxdart: ^0.27.7
  shared_preferences: ^2.0.17

dev_dependencies:
  build_runner: ^2.3.3
  envied_generator: ^0.3.0
  flutter_test:
    sdk: flutter

  very_good_analysis: ^3.1.0

flutter:
  uses-material-design: true
  generate: true
