name: player_repository
description: Player repository
version: 0.0.1
publish_to: none

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  common_models:
    path: ../common_models
  just_audio: ^0.9.32
  just_audio_mpv: ^0.1.6
  spotify_sdk: ^2.3.0

dev_dependencies:
  very_good_analysis: ^4.0.0+1