name: common_models
description: Common models
version: 0.0.1
publish_to: none

environment:
  sdk: '>=3.0.0'

dependencies:
  equatable: ^2.0.5
  hive: ^2.2.3

dev_dependencies:
  build_runner: ^2.4.2
  hive_generator: ^2.0.0
  very_good_analysis: ^4.0.0+1