name: common_models
description: Common models
version: 0.0.1
publish_to: none

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  equatable: ^2.0.5

dev_dependencies:
  very_good_analysis: ^4.0.0+1